/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class projectboarding_SeatingMethod */

#ifndef _Included_projectboarding_SeatingMethod
#define _Included_projectboarding_SeatingMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     projectboarding_SeatingMethod
 * Method:    convert2ArrayToArrayList
 * Signature: ([[Lprojectboarding/Cell;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_projectboarding_SeatingMethod_convert2ArrayToArrayList
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
