/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class projectboarding_PlaneDimension */

#ifndef _Included_projectboarding_PlaneDimension
#define _Included_projectboarding_PlaneDimension
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     projectboarding_PlaneDimension
 * Method:    getAllSeats
 * Signature: ()[[Lprojectboarding/Cell;
 */
JNIEXPORT jobjectArray JNICALL Java_projectboarding_PlaneDimension_getAllSeats
  (JNIEnv *, jobject);

/*
 * Class:     projectboarding_PlaneDimension
 * Method:    getPrioritySeats
 * Signature: ()[[Lprojectboarding/Cell;
 */
JNIEXPORT jobjectArray JNICALL Java_projectboarding_PlaneDimension_getPrioritySeats
  (JNIEnv *, jobject);

/*
 * Class:     projectboarding_PlaneDimension
 * Method:    getNormalSeats
 * Signature: ()[[Lprojectboarding/Cell;
 */
JNIEXPORT jobjectArray JNICALL Java_projectboarding_PlaneDimension_getNormalSeats
  (JNIEnv *, jobject);

/*
 * Class:     projectboarding_PlaneDimension
 * Method:    getNumberOfPriorityRows
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_projectboarding_PlaneDimension_getNumberOfPriorityRows
  (JNIEnv *, jobject);

/*
 * Class:     projectboarding_PlaneDimension
 * Method:    getNumberOfNormalRows
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_projectboarding_PlaneDimension_getNumberOfNormalRows
  (JNIEnv *, jobject);

/*
 * Class:     projectboarding_PlaneDimension
 * Method:    totalNumberOfRows
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_projectboarding_PlaneDimension_totalNumberOfRows
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
